import "@/app/ui/globals.css";
import { geistSans } from "@/app/ui/fonts";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} bg-background text-foreground antialiased`}>{children}</body>
    </html>
  );
}
